### ISSUE TITLE
pm_Form_Simple contains 1 abstract method

### ISSUE THREAD

**Issue by ksm2** [plesk/pm-api-stubs#5]
Hi,
when using your API stubs, PHP throws the following error:
_PHP Fatal error:_  **Class pm_Form_Simple contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend_Validate_Interface::getMessages)** in /home/moellers/Projects/Baqend/baqend-plesk/src/plib/vendor/plesk/pm-api-stubs/pm/Form/Simple.php on line 10

I am using the latest stubs and Zend Framework 1 releases.
Could you provide a fix and implement the `getMessages` method?
If you like, I can propose a PR for that.

Kind regards,
Konstantin

**Comment by xgin** [comment]
Thank you for reporting.
The issue should be fixed by inheriting of Zend_Form class.

**Comment by ksm2** [comment]
Thanks for the quick response! My tests are now working 👍
